export LD_LIBRARY_PATH=...

cd build
cmake -G Ninja \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER=... \
  -DCMAKE_C_COMPILER=... \
  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;" \
  -DLLVM_TARGETS_TO_BUILD=X86 \
  -DLLVM_TARGET_ARCH=x86_64 \
  -DLLVM_INCLUDE_EXAMPLES=OFF \
  -DLLVM_LIBDIR_SUFFIX=64 \
  ../llvm
